/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.BadConsequence;
import javax.swing.JLabel;

/**
 *
 * @author Dani
 */
public class PendingBadConsequenceView extends javax.swing.JPanel {
    
    BadConsequence pendingbcModel;
    /**
     * Creates new form PendingBadConsequenceView
     */
    public PendingBadConsequenceView() {
        initComponents();
    }
    
    public void setPendingBadConsequence(BadConsequence bc)
    {
        pendingbcModel = bc;
        
        jLabelPendingBadConsequenceText.setText(pendingbcModel.getText());
        repaint();
    }
    
    public JLabel getJLabelPendingBC()
    {
        return jLabelPendingBadConsequenceText;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelTitleIcon = new javax.swing.JLabel();
        jLabelPendingBadConsequenceText = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));

        jLabelTitle.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabelTitle.setText("Mal Rollo Pendiente");

        jLabelTitleIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/badConsequenceView/biblethump.png"))); // NOI18N

        jLabelPendingBadConsequenceText.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabelPendingBadConsequenceText.setText("Sin mal rollo pendiente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitleIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPendingBadConsequenceText)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(360, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTitleIcon)
                    .addComponent(jLabelTitle))
                .addGap(18, 18, 18)
                .addComponent(jLabelPendingBadConsequenceText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelPendingBadConsequenceText;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTitleIcon;
    // End of variables declaration//GEN-END:variables
}
