/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.CultistPlayer;
import NapakalakiGame.Napakalaki;
import NapakalakiGame.Player;
import NapakalakiGame.Treasure;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Dani
 */
public class PlayerView extends javax.swing.JPanel {
    
    private Player playerModel;
    private Napakalaki napakalakiModel;
    
    /**
     * Creates new form PlayerView
     */
    public PlayerView() {
        initComponents();
    }
    
    public void setPlayer(Player p)
    {
        playerModel = p;
        jLabelNameStatus.setText(p.getName());
        jLabelLevelStatus.setText(String.valueOf(p.getLevels()));
        jLabelCombatLevelStatus.setText(String.valueOf(p.getCombatLevel()));
        jLabelEnemyStatus.setText(p.getEnemy().getName());
        
        if (p instanceof CultistPlayer)
            jLabelCultistPlayerStatus.setText("Si");
        else
            jLabelCultistPlayerStatus.setText("No");
        
        if (p.canISteal())
            jLabelCanIStealStatus.setText("Si");
        else
            jLabelCanIStealStatus.setText("No");
        
        this.fillTreasurePanel(jPanelVisibleTreasures,playerModel.getVisibleTreasures());
        this.fillTreasurePanel(jPanelHiddenTreasures,playerModel.getHiddenTreasures());
        
        pendingBadConsequenceView.setPendingBadConsequence(p.getPendingBadConsequence());
        repaint();
        revalidate();
    }
    
    public void setNapakalaki(Napakalaki game)
    {
        napakalakiModel = game;
    }
    
    private void fillTreasurePanel (JPanel aPanel, ArrayList<Treasure> aList) 
    {
        // Se elimina la información antigua, si la hubiera
        aPanel.removeAll();
        // Se recorre la lista de tesoros construyendo y añadiendo sus vistas
        // al panel
        for (Treasure t : aList) 
        {
            TreasureView aTreasureView = new TreasureView();
            aTreasureView.setTreasure (t);
            aTreasureView.setVisible (true);
            aPanel.add (aTreasureView);
        }
        // Se fuerza la actualización visual del panel
        aPanel.repaint();
    }
    
    private ArrayList<Treasure> getSelectedTreasures(JPanel aPanel) 
    {
        // Se recorren los tesoros que contiene el panel,
        // almacenando en un vector aquellos que están seleccionados.
        // Finalmente se devuelve dicho vector.
        TreasureView tv;
        ArrayList<Treasure> output = new ArrayList();
        for (Component c : aPanel.getComponents()) 
        {
            tv = (TreasureView) c;
            if ( tv.isSelected() )
            output.add ( tv.getTreasure() );
        }
        
        return output;
    }
    
    public JButton getButtonSteal()
    {
        return jButtonStealTreasure;
    }
    public JButton getButtonMakeTreasureVisible()
    {
        return jButtonMakeTreasureVisible;
    }
    public JButton getButtonDiscardAllTreasures()
    {
        return jButtonDiscardAllTreasures;
    }
    public JButton getButtonDiscardTreasure()
    {
        
        return jButtonDiscardTreasure;
    }
    public JLabel getPendingBCText()
    {
        return pendingBadConsequenceView.getJLabelPendingBC();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelName = new javax.swing.JLabel();
        jLabelLevel = new javax.swing.JLabel();
        jLabelCombatLevel = new javax.swing.JLabel();
        jLabelEnemy = new javax.swing.JLabel();
        jLabelCanISteal = new javax.swing.JLabel();
        jLabelCultistPlayer = new javax.swing.JLabel();
        jLabelNameStatus = new javax.swing.JLabel();
        jLabelLevelStatus = new javax.swing.JLabel();
        jLabelCombatLevelStatus = new javax.swing.JLabel();
        jLabelCultistPlayerStatus = new javax.swing.JLabel();
        jLabelEnemyStatus = new javax.swing.JLabel();
        jLabelCanIStealStatus = new javax.swing.JLabel();
        jPanelVisibleTreasures = new javax.swing.JPanel();
        jPanelHiddenTreasures = new javax.swing.JPanel();
        jLabelPlayerVisibleTreasuresTitle = new javax.swing.JLabel();
        jLabelNameIcon = new javax.swing.JLabel();
        jLabelLevelIcon = new javax.swing.JLabel();
        jLabelCombatLevelIcon = new javax.swing.JLabel();
        jLabelEnemyIcon = new javax.swing.JLabel();
        jLabelCanIStealIcon = new javax.swing.JLabel();
        jLabelCultistPlayerIcon = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelPlayerHiddenTreasuresTitle = new javax.swing.JLabel();
        jLabelActionsTitle = new javax.swing.JLabel();
        jButtonStealTreasure = new javax.swing.JButton();
        jButtonMakeTreasureVisible = new javax.swing.JButton();
        jButtonDiscardTreasure = new javax.swing.JButton();
        jButtonDiscardAllTreasures = new javax.swing.JButton();
        jLabelVisibleTreasuresIcon = new javax.swing.JLabel();
        jLabelHiddenTreasuresIcon = new javax.swing.JLabel();
        pendingBadConsequenceView = new GUI.PendingBadConsequenceView();
        jLabelMakeTreasureVisibleWarning = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelName.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabelName.setText("Nombre:");

        jLabelLevel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabelLevel.setText("Nivel:");

        jLabelCombatLevel.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabelCombatLevel.setText("Nivel de combate:");

        jLabelEnemy.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabelEnemy.setText("Enemigo:");

        jLabelCanISteal.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabelCanISteal.setText("¿Puedo robar?:");

        jLabelCultistPlayer.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabelCultistPlayer.setText("¿Sectario?:");

        jLabelNameStatus.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabelNameStatus.setText("<undefined>");

        jLabelLevelStatus.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabelLevelStatus.setText("<undefined>");

        jLabelCombatLevelStatus.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabelCombatLevelStatus.setText("<undefined>");

        jLabelCultistPlayerStatus.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabelCultistPlayerStatus.setText("<undefined>");

        jLabelEnemyStatus.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabelEnemyStatus.setText("<undefined>");

        jLabelCanIStealStatus.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabelCanIStealStatus.setText("<undefined>");

        jPanelVisibleTreasures.setBackground(new java.awt.Color(255, 255, 204));
        jPanelVisibleTreasures.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0), 2));
        jPanelVisibleTreasures.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanelHiddenTreasures.setBackground(new java.awt.Color(204, 255, 204));
        jPanelHiddenTreasures.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102), 2));
        jPanelHiddenTreasures.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelPlayerVisibleTreasuresTitle.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabelPlayerVisibleTreasuresTitle.setText("Tesoros Equipados");

        jLabelNameIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/playerView/name.png"))); // NOI18N

        jLabelLevelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/playerView/level.png"))); // NOI18N

        jLabelCombatLevelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/playerView/combatlevel.png"))); // NOI18N

        jLabelEnemyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/playerView/enemy.png"))); // NOI18N

        jLabelCanIStealIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/playerView/canisteal.png"))); // NOI18N

        jLabelCultistPlayerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/playerView/cultist.png"))); // NOI18N

        jLabelTitle.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabelTitle.setText("Estado del jugador");

        jLabelPlayerHiddenTreasuresTitle.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabelPlayerHiddenTreasuresTitle.setText("Tesoros Ocultos");

        jLabelActionsTitle.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabelActionsTitle.setText("Acciones");

        jButtonStealTreasure.setBackground(new java.awt.Color(254, 192, 132));
        jButtonStealTreasure.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jButtonStealTreasure.setText("Robar Tesoro");
        jButtonStealTreasure.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        jButtonStealTreasure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStealTreasureActionPerformed(evt);
            }
        });

        jButtonMakeTreasureVisible.setBackground(new java.awt.Color(252, 124, 123));
        jButtonMakeTreasureVisible.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jButtonMakeTreasureVisible.setText("Equipar Tesoro");
        jButtonMakeTreasureVisible.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 2, true));
        jButtonMakeTreasureVisible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMakeTreasureVisibleActionPerformed(evt);
            }
        });

        jButtonDiscardTreasure.setBackground(new java.awt.Color(153, 255, 153));
        jButtonDiscardTreasure.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jButtonDiscardTreasure.setText("Descartar Tesoro");
        jButtonDiscardTreasure.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 51), 2, true));
        jButtonDiscardTreasure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiscardTreasureActionPerformed(evt);
            }
        });

        jButtonDiscardAllTreasures.setBackground(new java.awt.Color(50, 174, 236));
        jButtonDiscardAllTreasures.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jButtonDiscardAllTreasures.setText("Descartar Todos los Tesoros");
        jButtonDiscardAllTreasures.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 2, true));
        jButtonDiscardAllTreasures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiscardAllTreasuresActionPerformed(evt);
            }
        });

        jLabelVisibleTreasuresIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/playerView/visibletreasures.png"))); // NOI18N

        jLabelHiddenTreasuresIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/playerView/hiddentreasures.png"))); // NOI18N

        jLabelMakeTreasureVisibleWarning.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        jLabelMakeTreasureVisibleWarning.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelLevelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelLevel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelLevelStatus))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNameIcon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNameStatus))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCombatLevelIcon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCombatLevel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCombatLevelStatus))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCanIStealIcon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCanISteal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelCanIStealStatus))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabelEnemyIcon)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelEnemy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelEnemyStatus))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCultistPlayerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCultistPlayer)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelCultistPlayerStatus))
                            .addComponent(jLabelTitle))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanelVisibleTreasures, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabelHiddenTreasuresIcon)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelPlayerHiddenTreasuresTitle))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabelVisibleTreasuresIcon)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelPlayerVisibleTreasuresTitle)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanelHiddenTreasures, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonStealTreasure, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonMakeTreasureVisible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonDiscardTreasure, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonDiscardAllTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelMakeTreasureVisibleWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelActionsTitle)
                            .addComponent(pendingBadConsequenceView, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabelTitle)
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNameIcon, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelName)
                                .addComponent(jLabelNameStatus)))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelLevel)
                                    .addComponent(jLabelLevelStatus)))
                            .addComponent(jLabelLevelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCombatLevelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelCombatLevel)
                                .addComponent(jLabelCombatLevelStatus)))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEnemyIcon)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelEnemy)
                                .addComponent(jLabelEnemyStatus)))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCanIStealIcon)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelCanISteal)
                                .addComponent(jLabelCanIStealStatus)))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCultistPlayerIcon)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelCultistPlayer)
                                .addComponent(jLabelCultistPlayerStatus))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPlayerVisibleTreasuresTitle)
                            .addComponent(jLabelVisibleTreasuresIcon))
                        .addGap(18, 18, 18)
                        .addComponent(jPanelVisibleTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPlayerHiddenTreasuresTitle, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelHiddenTreasuresIcon, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addComponent(jPanelHiddenTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelActionsTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabelMakeTreasureVisibleWarning, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStealTreasure, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMakeTreasureVisible, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDiscardTreasure, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDiscardAllTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(pendingBadConsequenceView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStealTreasureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStealTreasureActionPerformed
        // TODO add your handling code here:
        napakalakiModel.getCurrentPlayer().stealTreasure();
        jButtonStealTreasure.setEnabled(false);
        
        NapakalakiView.getSoundButtonSelect().Play(false);
        setPlayer (napakalakiModel.getCurrentPlayer());
    }//GEN-LAST:event_jButtonStealTreasureActionPerformed

    private void jButtonMakeTreasureVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMakeTreasureVisibleActionPerformed
        // TODO add your handling code here:
        ArrayList<Treasure> selHidden = getSelectedTreasures (jPanelHiddenTreasures);
        if (napakalakiModel.getCurrentPlayer().getPendingBadConsequence().isEmpty())
        {
            NapakalakiView.getSoundButtonSelect().Play(false);
            napakalakiModel.makeTreasuresVisible (selHidden);
            jLabelMakeTreasureVisibleWarning.setText("");
        } 
        else
        {
            NapakalakiView.getSoundButtonSelectCancel().Play(false);
            jLabelMakeTreasureVisibleWarning.setText("Tienes que cumplir el mal rollo primero.");
        }

        setPlayer (napakalakiModel.getCurrentPlayer());
    }//GEN-LAST:event_jButtonMakeTreasureVisibleActionPerformed

    private void jButtonDiscardTreasureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiscardTreasureActionPerformed
        // TODO add your handling code here:
        ArrayList<Treasure> selHidden = getSelectedTreasures (jPanelHiddenTreasures);
        ArrayList<Treasure> selVisible = getSelectedTreasures (jPanelVisibleTreasures);
        
        napakalakiModel.discardHiddenTreasures(selHidden);
        napakalakiModel.discardVisibleTreasures(selVisible);
        
        NapakalakiView.getSoundButtonSelect().Play(false);
        setPlayer (napakalakiModel.getCurrentPlayer());
    }//GEN-LAST:event_jButtonDiscardTreasureActionPerformed

    private void jButtonDiscardAllTreasuresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiscardAllTreasuresActionPerformed
        // TODO add your handling code here:
        
        playerModel.discardAllTreasures();
        
        NapakalakiView.getSoundButtonSelect().Play(false);
        setPlayer (napakalakiModel.getCurrentPlayer());
    }//GEN-LAST:event_jButtonDiscardAllTreasuresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDiscardAllTreasures;
    private javax.swing.JButton jButtonDiscardTreasure;
    private javax.swing.JButton jButtonMakeTreasureVisible;
    private javax.swing.JButton jButtonStealTreasure;
    private javax.swing.JLabel jLabelActionsTitle;
    private javax.swing.JLabel jLabelCanISteal;
    private javax.swing.JLabel jLabelCanIStealIcon;
    private javax.swing.JLabel jLabelCanIStealStatus;
    private javax.swing.JLabel jLabelCombatLevel;
    private javax.swing.JLabel jLabelCombatLevelIcon;
    private javax.swing.JLabel jLabelCombatLevelStatus;
    private javax.swing.JLabel jLabelCultistPlayer;
    private javax.swing.JLabel jLabelCultistPlayerIcon;
    private javax.swing.JLabel jLabelCultistPlayerStatus;
    private javax.swing.JLabel jLabelEnemy;
    private javax.swing.JLabel jLabelEnemyIcon;
    private javax.swing.JLabel jLabelEnemyStatus;
    private javax.swing.JLabel jLabelHiddenTreasuresIcon;
    private javax.swing.JLabel jLabelLevel;
    private javax.swing.JLabel jLabelLevelIcon;
    private javax.swing.JLabel jLabelLevelStatus;
    private javax.swing.JLabel jLabelMakeTreasureVisibleWarning;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNameIcon;
    private javax.swing.JLabel jLabelNameStatus;
    private javax.swing.JLabel jLabelPlayerHiddenTreasuresTitle;
    private javax.swing.JLabel jLabelPlayerVisibleTreasuresTitle;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelVisibleTreasuresIcon;
    private javax.swing.JPanel jPanelHiddenTreasures;
    private javax.swing.JPanel jPanelVisibleTreasures;
    private GUI.PendingBadConsequenceView pendingBadConsequenceView;
    // End of variables declaration//GEN-END:variables
}
