/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.Sound;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;


/**
 *
 * @author danidiaz
 */
public class PlayerNamesCapture extends javax.swing.JDialog {

    private ArrayList<String> names = new ArrayList();
    Sound titleSound;
    
    /**
     * Creates new form PlayerNamesCapture
     */
    public PlayerNamesCapture(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        getContentPane().setBackground(new java.awt.Color(153, 204, 255));
        initComponents();
        this.addWindowListener (new WindowAdapter() 
        {
            @Override
            public void windowClosing (WindowEvent e) {System.exit(0);}
        });
        
        titleSound = new Sound("/GUI/sound/title.wav");
        titleSound.Play(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDesc = new javax.swing.JLabel();
        jlPlayer2 = new javax.swing.JLabel();
        jlPlayer3 = new javax.swing.JLabel();
        jtfPlayer1 = new javax.swing.JTextField();
        jtfPlayer2 = new javax.swing.JTextField();
        jtfPlayer3 = new javax.swing.JTextField();
        jButtonPlay = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jlPlayer4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Napakalaki");
        setBackground(new java.awt.Color(204, 204, 255));

        jLabelDesc.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabelDesc.setText("Escribe los nombres de los jugadores para empezar.");

        jlPlayer2.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jlPlayer2.setText("Jugador 2");

        jlPlayer3.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jlPlayer3.setText("Jugador 3");

        jtfPlayer1.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jtfPlayer1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jtfPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPlayer1ActionPerformed(evt);
            }
        });

        jtfPlayer2.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jtfPlayer2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jtfPlayer3.setFont(new java.awt.Font("Bell MT", 1, 14)); // NOI18N
        jtfPlayer3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jButtonPlay.setBackground(new java.awt.Color(254, 192, 132));
        jButtonPlay.setFont(new java.awt.Font("Bell MT", 1, 15)); // NOI18N
        jButtonPlay.setText("Jugar");
        jButtonPlay.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        jButtonPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayActionPerformed(evt);
            }
        });

        jButtonCancel.setBackground(new java.awt.Color(252, 124, 123));
        jButtonCancel.setFont(new java.awt.Font("Bell MT", 1, 15)); // NOI18N
        jButtonCancel.setText("Cancelar");
        jButtonCancel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 2, true));
        jButtonCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabelTitle.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jLabelTitle.setText("¡Bienvenido a Napakalaki!");

        jlPlayer4.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jlPlayer4.setText("Jugador 1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setText("Realizado por: Daniel Díaz Pareja");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTitle)
                                    .addComponent(jLabelDesc)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtfPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addComponent(jlPlayer4)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addComponent(jtfPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(31, 31, 31))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jlPlayer2)
                                                .addGap(57, 57, 57)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jtfPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jlPlayer3)
                                                .addGap(23, 23, 23))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(jButtonPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)
                                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabelTitle)
                .addGap(18, 18, 18)
                .addComponent(jLabelDesc)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPlayer2)
                    .addComponent(jlPlayer3)
                    .addComponent(jlPlayer4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPlayer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPlayer1ActionPerformed

    private void jButtonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayActionPerformed
        // TODO add your handling code here:
        names.add(jtfPlayer1.getText());
        names.add(jtfPlayer2.getText());
        names.add(jtfPlayer3.getText());
        
        Sound jButtonPlay = new Sound("/GUI/sound/jButtonPlay.wav");
        jButtonPlay.Play(false);
        titleSound.Stop();
        NapakalakiView.getSoundMainTheme().Play(true);
        this.dispose();
    }//GEN-LAST:event_jButtonPlayActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * @brief Hace la ventana visible, captura los nombres y los devuelve
     * @return Nombres de los jugadores
     */
    public ArrayList<String> getNames() 
    {
        this.setVisible(true);
        return names;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonPlay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDesc;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jlPlayer2;
    private javax.swing.JLabel jlPlayer3;
    private javax.swing.JLabel jlPlayer4;
    private javax.swing.JTextField jtfPlayer1;
    private javax.swing.JTextField jtfPlayer2;
    private javax.swing.JTextField jtfPlayer3;
    // End of variables declaration//GEN-END:variables


}
