/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.Sound;
import NapakalakiGame.Treasure;
import java.awt.Color;

/**
 *
 * @author Dani
 */
public class TreasureView extends javax.swing.JPanel {
    private boolean selected = false;
    private Treasure treasureModel;
    Sound treasureUnselect = new Sound("/GUI/sound/TreasureUnselect.wav");;
    
    /**
     * Creates new form TreasureView
     */
    public TreasureView() {
        initComponents();
    }
    
    public void setTreasure(Treasure t){
        treasureModel = t;
        jLabelTreasureIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/images/treasures/"+t.getName()+".jpg")));
        repaint();
        revalidate();
    }
    
    public boolean isSelected()
    {
        return selected;
    }
    
    public Treasure getTreasure()
    {
        return treasureModel;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTreasureIcon = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTreasureIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTreasureIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        if (!selected)
        {
            selected = true;
            NapakalakiView.getSoundButtonSelect().Play(false);
            
        }
        else
        {
            selected=false;
            treasureUnselect.Play(false);
        }
        
        setBackground(Color.ORANGE);
        this.setOpaque(selected);
        repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTreasureIcon;
    // End of variables declaration//GEN-END:variables
}
